version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 12
  pre_build:
    commands:
      - ./scripts/prebuild.sh
  build:
    commands:
      - ./scripts/build.sh
  post_build:
    commands:
      - ./scripts/deploy.sh